from VYPcode.operations import ALIAS
from output import Output


def print_code_header():
    Output.print(
        '''\
#!/bin/vypint
# VYPcode: 1.0
# Generated by: xhorky23 xmucka03'''
    )


def print_code_aliases():
    Output.print(ALIAS("ACC", "$0"))
