import sys
import ply.lex as lex
import ply.yacc as yacc

from src.instructionsTape import MAIN_INSTRUCTION_TAPE
from src.output import Output
from src.tokens import *
from src.rules.rules import *


lexer = lex.lex(debug=True)
parser = yacc.yacc(outputdir="generated", debug=True, start="program")


def parse():
    with open(sys.argv[1], 'r') as content_file:  # todo check for error in arguments
        parser.parse(content_file.read(), debug=True)


parse()
Output.print('''\
#!/bin/vypint
# VYPcode: 1.0
# Generated by: xhorky23 xmucka03''')
print(MAIN_INSTRUCTION_TAPE)


