import sys

from src.instructionsTape import MAIN_INSTRUCTION_TAPE


class Printer:
    file = None

    def __init__(self, file):
        if file is not None:
            self.file = open(file, "w")

    def write(self, s):
        print(str(s), file=(self.file if self.file else sys.stdout))

    def error(self, s):
        print(str(s), file=sys.stderr)

    def close(self):
        if self.file:
            self.file.close()

    def print(self):
        self.write(
            '#!/bin/vypint\n' +
            '# VYPcode: 1.0\n' +
            '# Generated by: xhorky23 xmucka03'
        )
        MAIN_INSTRUCTION_TAPE.add_constant_section()
        for instrunction in MAIN_INSTRUCTION_TAPE.get_instructions():
            self.write(instrunction)


Output = Printer(sys.argv[2] if len(sys.argv) > 2 else None)